# Generated by Django 5.2.4 on 2025-08-27 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_course_owner_lesson_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="desc",
            field=models.CharField(blank=True, null=True, verbose_name="Desc"),
        ),
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="course/", verbose_name="Course picture"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="desc",
            field=models.CharField(blank=True, null=True, verbose_name="Desc"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="course/", verbose_name="Lesson picture"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="url",
            field=models.CharField(blank=True, null=True, verbose_name="Video url"),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_course",
                        to="lms.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
